<?php
/**
 *  Install Add-ons
 *
 *  The following code will include all 4 premium Add-Ons in your theme.
 *  Please do not attempt to include a file which does not exist. This will produce an error.
 *
 *  The following code assumes you have a folder 'add-ons' inside your theme.
 *
 *  IMPORTANT
 *  Add-ons may be included in a premium theme/plugin as outlined in the terms and conditions.
 *  For more information, please read:
 *  - http://www.advancedcustomfields.com/terms-conditions/
 *  - http://www.advancedcustomfields.com/resources/getting-started/including-lite-mode-in-a-plugin-theme/
 */

// Add-ons
// include_once('add-ons/acf-repeater/acf-repeater.php');
// include_once('add-ons/acf-gallery/acf-gallery.php');
// include_once('add-ons/acf-flexible-content/acf-flexible-content.php');
// include_once( 'add-ons/acf-options-page/acf-options-page.php' );


/**
 *  Register Field Groups
 *
 *  The register_field_group function accepts 1 array which holds the relevant data to register a field group
 *  You may edit the array as you see fit. However, this may result in errors if the array is not compatible with ACF
 */

if(function_exists("register_field_group"))
{
  register_field_group(array (
    'id' => 'acf_custom-header-settings',
    'title' => 'Custom Header Settings',
    'fields' => array (
      array (
        'key' => 'field_51c016b6279a8',
        'label' => __('Highlighted Header', 'venera' ),
        'name' => '',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_51c016e6279a9',
        'label' => __('Show Highlighted Header', 'venera' ),
        'name' => 'show_highlighted_header',
        'type' => 'true_false',
        'instructions' => __('Check this field if you want to show highlighted header', 'venera'),
        'message' => 'Show highlighted header',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_51c017d6279aa',
        'label' => __('Header Title', 'venera' ),
        'name' => 'header_title',
        'type' => 'text',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51c016e6279a9',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_51c01835279ab',
        'label' => __('Header Sub Title', 'venera' ),
        'name' => 'header_sub_title',
        'type' => 'text',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51c016e6279a9',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_51c01859279ac',
        'label' => __('Same Line Title', 'venera' ),
        'name' => 'same_line_title',
        'type' => 'true_false',
        'instructions' => __('Check this field if you want to show title and sub title on the same line', 'venera'),
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51c016e6279a9',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'message' => 'Show title on the same line as sub title',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_51c018d3279ad',
        'label' => __('Custom Background', 'venera' ),
        'name' => 'header_custom_background',
        'type' => 'true_false',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51c016e6279a9',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'message' => 'Set custom background for header',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_51c01a40ecc83',
        'label' => __('Solid Color', 'venera' ),
        'name' => 'header_solid_color',
        'type' => 'color_picker',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51c018d3279ad',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
      ),
      array (
        'key' => 'field_51c01b1cecc84',
        'label' => __('Image as a Background', 'venera' ),
        'name' => 'header_background_image',
        'type' => 'image',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51c018d3279ad',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'save_format' => 'object',
        'preview_size' => 'thumbnail',
        'library' => 'all',
      ),
      array (
        'key' => 'field_51c01ca903070',
        'label' => __('Title Font Color', 'venera' ),
        'name' => 'header_custom_title_font_color',
        'type' => 'color_picker',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51c018d3279ad',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
      ),
      array (
        'key' => 'field_51c029136f0b5',
        'label' => __('Sub Title Font Color', 'venera' ),
        'name' => 'header_custom_sub_title_font_color',
        'type' => 'color_picker',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51c018d3279ad',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
      ),
      array (
        'key' => 'field_51c02bb8f4ea8',
        'label' => __('Add Icon or Image to Header', 'venera' ),
        'name' => 'add_icon_or_image_to_header',
        'type' => 'true_false',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51c016e6279a9',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'message' => 'Enable Icon or Image support for header',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_51c02c3e22945',
        'label' => __('Icon Name (e.g. icon-cog)', 'venera' ),
        'name' => 'header_icon_class',
        'type' => 'text',
        'instructions' => __('Type the icon name you want to use from the list of available FontAwesome icons: <a href="http://fortawesome.github.io/Font-Awesome/icons/" target="_blank">http://fortawesome.github.io/Font-Awesome/icons/</a>', 'venera'),
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51c02bb8f4ea8',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_51c02c7522946',
        'label' => __('Image', 'venera' ),
        'name' => 'header_image',
        'type' => 'image',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51c02bb8f4ea8',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'save_format' => 'object',
        'preview_size' => 'thumbnail',
        'library' => 'all',
      ),
      array (
        'key' => 'field_51c02cb822947',
        'label' => __('Icon/Image Position', 'venera' ),
        'name' => 'header_icon_position',
        'type' => 'select',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51c02bb8f4ea8',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'choices' => array (
          'left' => __('Align Left', 'venera'),
          'right' => __('Align Right', 'venera'),
        ),
        'default_value' => 'left',
        'allow_null' => 0,
        'multiple' => 0,
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'venera_portfolio',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'page',
          'order_no' => 0,
          'group_no' => 1,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_options-appearance',
    'title' => 'Options: Appearance',
    'fields' => array (
      array (
        'key' => 'field_51d537189ed0b',
        'label' => __('Color Scheme', 'venera' ),
        'name' => '',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_51f4122a75204',
        'label' => __('Color Scheme Message', 'venera' ),
        'name' => '',
        'type' => 'message',
        'message' => '<h1>Color Scheme Settings</h1>
  <p class="howto">These settings define a color scheme you want to use for the website, you can also set your custom colors by clicking the "Allow to override..." checkmark and defining your custom colors in other sections of "Options" panel.</p>',
      ),
      array (
        'key' => 'field_51d535c59ed09',
        'label' => __('Color Scheme', 'venera' ),
        'name' => 'color_scheme',
        'type' => 'radio',
        'required' => 1,
        'choices' => array (
          'color1' => __('Color Theme 1', 'venera'),
          'color2' => __('Color Theme 2', 'venera'),
          'color3' => __('Color Theme 3', 'venera'),
          'color4' => __('Color Theme 4', 'venera'),
        ),
        'other_choice' => 0,
        'save_other_choice' => 0,
        'default_value' => 'color1',
        'layout' => 'vertical',
      ),
      array (
        'key' => 'field_51d5366a9ed0a',
        'label' => __('Allow to override color scheme settings', 'venera' ),
        'name' => 'allow_overwrite_of_color_scheme',
        'type' => 'true_false',
        'message' => 'Yes, allow to override color settings',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_51d4905e6be8f',
        'label' => __('General', 'venera' ),
        'name' => '',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_51f411db82013',
        'label' => __('General Message', 'venera' ),
        'name' => '',
        'type' => 'message',
        'message' => '<h1>General Appearance Settings</h1>
  <p class="howto">Define general settings for your theme.</p>',
      ),
      array (
        'key' => 'field_51d3caf6877fb',
        'label' => __('Body Background Color', 'venera' ),
        'name' => 'background_solid_color',
        'type' => 'color_picker',
        'default_value' => '#edece3',
      ),
      array (
        'key' => 'field_51d3fb7fe84c4',
        'label' => __('Text Color', 'venera' ),
        'name' => 'text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51d3fbf0e84c5',
        'label' => __('Headings Text Color', 'venera' ),
        'name' => 'headings_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51f9400221c5c',
        'label' => __('Logo type', 'venera' ),
        'name' => 'logo_type',
        'type' => 'radio',
        'choices' => array (
          'image' => 'Image',
          'text' => 'Text',
        ),
        'other_choice' => 0,
        'save_other_choice' => 0,
        'default_value' => 'text',
        'layout' => 'horizontal',
      ),
      array (
        'key' => 'field_51f9406c21c5d',
        'label' => __('Logo Image', 'venera' ),
        'name' => 'logo_image',
        'type' => 'image',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51f9400221c5c',
              'operator' => '==',
              'value' => 'image',
            ),
          ),
          'allorany' => 'all',
        ),
        'save_format' => 'url',
        'preview_size' => 'thumbnail',
        'library' => 'all',
      ),
      array (
        'key' => 'field_51f942318f9f7',
        'label' => __('Logo Image Width (e.g. 100px)', 'venera' ),
        'name' => 'logo_image_width',
        'type' => 'text',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51f9400221c5c',
              'operator' => '==',
              'value' => 'image',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '100px',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_51f945049fa7d',
        'label' => __('Logo Font Size (e.g. 20px)', 'venera' ),
        'name' => 'logo_font_size',
        'type' => 'text',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51f9400221c5c',
              'operator' => '==',
              'value' => 'text',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '24px',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_51f9409121c5e',
        'label' => __('Logo Text', 'venera' ),
        'name' => 'logo_text',
        'type' => 'text',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51f9400221c5c',
              'operator' => '==',
              'value' => 'text',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => 'THEMEVENERA',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_51e1eff7d2bc2',
        'label' => __('Flat Headers', 'venera' ),
        'name' => 'make_headers_flat',
        'type' => 'true_false',
        'instructions' => __('This will remove shadow and gloss from header borders', 'venera'),
        'message' => 'Make header borders flat',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_51d4907d6be90',
        'label' => __('Leader Board', 'venera' ),
        'name' => '',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_51f40ed6d7d5b',
        'label' => __('Leader Message', 'venera' ),
        'name' => '',
        'type' => 'message',
        'message' => '<h1>Leader Board</h1>
  <p class="howto">This settings control the leader section which is defined by inserting a "Content Slider" element from page builder or just assigning a class "section-leader" to a row.</p>',
      ),
      array (
        'key' => 'field_51d489f8a7cab',
        'label' => __('Background Color', 'venera' ),
        'name' => 'leader_board_background_solid_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51f3f4c3057b5',
        'label' => __('Background Image', 'venera' ),
        'name' => 'leader_board_background_image',
        'type' => 'image',
        'save_format' => 'url',
        'preview_size' => 'thumbnail',
        'library' => 'all',
      ),
      array (
        'key' => 'field_51d492a50db42',
        'label' => __('Primary Text Color', 'venera' ),
        'name' => 'leader_board_primary_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51d4942a0db43',
        'label' => __('Secondary Text Color', 'venera' ),
        'name' => 'leader_board_secondary_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51de110d1f6c2',
        'label' => __('Highlighted Text Color', 'venera' ),
        'name' => 'leader_board_highlight_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51d4909e6be91',
        'label' => __('Highlighted Block', 'venera' ),
        'name' => '',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_51f4103ff7f46',
        'label' => __('Highlighted Block Message', 'venera' ),
        'name' => '',
        'type' => 'message',
        'message' => '<h1>Highlighted Block</h1>
  <p class="howto">This settings control the highlighted section under the slider or leader board. It usually contains icons with features.</p>',
      ),
      array (
        'key' => 'field_51e0c4e60eb16',
        'label' => __('Make it flat', 'venera' ),
        'name' => 'highlighted_block_make_it_flat',
        'type' => 'true_false',
        'instructions' => __('This will remove gloss, shadows and borders from the highlighted block', 'venera'),
        'message' => 'Make highlighted block flat',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_51d48adda7cac',
        'label' => __('Background Color', 'venera' ),
        'name' => 'highlighted_block_background_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e0c85a21ef9',
        'label' => __('Icons Color', 'venera' ),
        'name' => 'highlighted_block_icons_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e0c51f0eb17',
        'label' => __('Headings Colors', 'venera' ),
        'name' => 'highlighted_block_headings_colors',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51d48f4b5ff2a',
        'label' => __('Text Color', 'venera' ),
        'name' => 'highlighted_block_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51d49ce124d11',
        'label' => __('CTA Block', 'venera' ),
        'name' => '',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_51f41098f7f47',
        'label' => __('Call to action message', 'venera' ),
        'name' => '',
        'type' => 'message',
        'message' => '<h1>Call to action block</h1>
  <p class="howto">This settings control the call to action block, usually separated from a regular content with a different, highlighted background which will allow it to pop and standout.</p>',
      ),
      array (
        'key' => 'field_51d48d2ea7cad',
        'label' => __('Background Color', 'venera' ),
        'name' => 'call_to_action_section_background',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51f40864454d7',
        'label' => __('Background Image', 'venera' ),
        'name' => 'call_to_action_section_background_image',
        'type' => 'image',
        'save_format' => 'url',
        'preview_size' => 'thumbnail',
        'library' => 'all',
      ),
      array (
        'key' => 'field_51d48f665ff2b',
        'label' => __('Text Color', 'venera' ),
        'name' => 'call_to_action_section_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_5213d830a387c',
        'label' => __('Fonts', 'venera' ),
        'name' => '',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_5213cef43e080',
        'label' => __('Google Fonts String', 'venera' ),
        'name' => 'web_fonts_href',
        'type' => 'text',
        'instructions' => __('The href string that you can copy from google web fonts website <a href="http://bit.ly/1d3nlc2">http://bit.ly/1d3nlc2</a>.<br/>Default value: <strong>http://fonts.googleapis.com/css?family=Oswald:400,700,300|Roboto+Condensed:300,400,700</strong>', 'venera'),
        'default_value' => 'http://fonts.googleapis.com/css?family=Oswald:400,700,300|Roboto+Condensed:300,400,700',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5214554588739',
        'label' => __('Base Font Settings', 'venera' ),
        'name' => '',
        'type' => 'message',
        'message' => '<h2>Base Font Settings</h2>',
      ),
      array (
        'key' => 'field_5213d7023e082',
        'label' => __('Base Font Family', 'venera' ),
        'name' => 'primary_font_family',
        'type' => 'text',
        'instructions' => __('Default value: <strong>"Roboto Condensed", "Helvetica Neue", Helvetica, Arial, sans-serif</strong>', 'venera'),
        'default_value' => '"Roboto Condensed", "Helvetica Neue", Helvetica, Arial, sans-serif',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5213e9b44a8d7',
        'label' => __('Base Font Size', 'venera' ),
        'name' => 'base_font_size',
        'type' => 'text',
        'instructions' => __('Default value: 16px', 'venera'),
        'default_value' => '16px',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5213e3c660746',
        'label' => __('Base Font Weight', 'venera' ),
        'name' => 'base_font_weight',
        'type' => 'text',
        'instructions' => __('Default font weight for the website. Default value: 300', 'venera'),
        'default_value' => 300,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5213e9e65e0f5',
        'label' => __('Base Line Height', 'venera' ),
        'name' => 'base_line_height',
        'type' => 'text',
        'instructions' => __('Default value: 24px', 'venera'),
        'default_value' => '24px',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5214555c8873a',
        'label' => __('Headings Fonts', 'venera' ),
        'name' => '',
        'type' => 'message',
        'message' => '<h2>Headings Fonts</h2>',
      ),
      array (
        'key' => 'field_5213d6743e081',
        'label' => __('Headings Font Family', 'venera' ),
        'name' => 'secondary_font_family',
        'type' => 'text',
        'instructions' => __('Default value: <strong>"Oswald", "Helvetica Neue", Helvetica, Arial, sans-serif</strong>', 'venera'),
        'default_value' => '"Oswald", "Helvetica Neue", Helvetica, Arial, sans-serif',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5213e1c56bfad',
        'label' => __('Headings Font Weight', 'venera' ),
        'name' => 'headings_font_weight',
        'type' => 'text',
        'instructions' => __('Font weight for headings. Default value: 400', 'venera'),
        'default_value' => 400,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_521453a257422',
        'label' => __('Navigation Fonts', 'venera' ),
        'name' => '',
        'type' => 'message',
        'message' => '<h2>Navigation Fonts</h2>',
      ),
      array (
        'key' => 'field_5213e746ed3a7',
        'label' => __('Navigation Font Family', 'venera' ),
        'name' => 'navigation_font_family',
        'type' => 'text',
        'instructions' => __('Default value: <strong>"Oswald", "Helvetica Neue", Helvetica, Arial, sans-serif</strong>', 'venera'),
        'default_value' => '"Oswald", "Helvetica Neue", Helvetica, Arial, sans-serif',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5213e35260745',
        'label' => __('Navigation Font Weight', 'venera' ),
        'name' => 'navigation_font_weight',
        'type' => 'text',
        'instructions' => __('Default value: 300', 'venera'),
        'default_value' => 300,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_521448108aaf4',
        'label' => __('Navigation Font Size', 'venera' ),
        'name' => 'navigation_font_size',
        'type' => 'text',
        'instructions' => __('Default: 18px', 'venera'),
        'default_value' => '18px',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5214531e1cfae',
        'label' => __('Button Fonts', 'venera' ),
        'name' => '',
        'type' => 'message',
        'message' => '<h2>Button Fonts</h2>',
      ),
      array (
        'key' => 'field_5213e71ded3a6',
        'label' => __('Buttons Font Family', 'venera' ),
        'name' => 'buttons_font_family',
        'type' => 'text',
        'instructions' => __('Default: <strong>"Oswald", "Helvetica Neue", Helvetica, Arial, sans-serif</strong>', 'venera'),
        'default_value' => '"Oswald", "Helvetica Neue", Helvetica, Arial, sans-serif',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5213e32860744',
        'label' => __('Buttons Font Weight', 'venera' ),
        'name' => 'buttons_font_weight',
        'type' => 'text',
        'instructions' => __('Default value: 300', 'venera'),
        'default_value' => 300,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_521453f961af2',
        'label' => __('Primary Font Weights', 'venera' ),
        'name' => '',
        'type' => 'message',
        'message' => '<h2>Primary Font Weights</h2>',
      ),
      array (
        'key' => 'field_5213de146bfa7',
        'label' => __('Primary Font Weight Bold', 'venera' ),
        'name' => 'primary_font_weight_bold',
        'type' => 'text',
        'instructions' => __('The weight of the bold primary font. Default: 700', 'venera'),
        'default_value' => 700,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5213de616bfa8',
        'label' => __('Primary Font Weight Normal', 'venera' ),
        'name' => 'primary_font_weight_normal',
        'type' => 'text',
        'instructions' => __('The weight of the normal primary font. Default: 400', 'venera'),
        'default_value' => 400,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5213de8d6bfa9',
        'label' => __('Primary Font Weight Thin', 'venera' ),
        'name' => 'primary_font_weight_thin',
        'type' => 'text',
        'instructions' => __('The weight of the thin primary font. Default: 300', 'venera'),
        'default_value' => 300,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5214543861af3',
        'label' => __('Secondary Font Weights', 'venera' ),
        'name' => '',
        'type' => 'message',
        'message' => '<h2>Secondary Font Weights</h2>',
      ),
      array (
        'key' => 'field_5213dea86bfaa',
        'label' => __('Secondary Font Weight Bold', 'venera' ),
        'name' => 'secondary_font_weight_bold',
        'type' => 'text',
        'instructions' => __('The weight of bold headings font. Default: 700', 'venera'),
        'default_value' => 700,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5213ded96bfab',
        'label' => __('Secondary Font Weight Normal', 'venera' ),
        'name' => 'secondary_font_weight_normal',
        'type' => 'text',
        'instructions' => __('The weight of normal headings font. Default: 400', 'venera'),
        'default_value' => 400,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5213def56bfac',
        'label' => __('Secondary Font Weight Thin', 'venera' ),
        'name' => 'secondary_font_weight_thin',
        'type' => 'text',
        'instructions' => __('The weight of thin headings font. Default: 300', 'venera'),
        'default_value' => 300,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-appearance',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_options-blog-posts',
    'title' => 'Options: Blog Posts',
    'fields' => array (
      array (
        'key' => 'field_51e8b3651cd20',
        'label' => __('Post', 'venera' ),
        'name' => '',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_51f58ef0fcc60',
        'label' => __('Make it Flat', 'venera' ),
        'name' => 'post_content_make_it_flat',
        'type' => 'true_false',
        'message' => 'Make post content flat',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_51e8b1fe1cd1b',
        'label' => __('Content Border Radius (e.g. 5px)', 'venera' ),
        'name' => 'post_content_radius',
        'type' => 'text',
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_51e8b29e1cd1c',
        'label' => __('Content Background', 'venera' ),
        'name' => 'post_content_background',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e8b2ca1cd1d',
        'label' => __('Content Padding (e.g. 20px)', 'venera' ),
        'name' => 'post_content_padding',
        'type' => 'text',
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_51f59439fe749',
        'label' => __('Headings Color', 'venera' ),
        'name' => 'post_content_headings_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51f593e6fe748',
        'label' => __('Text Color', 'venera' ),
        'name' => 'post_content_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51f5949efe74a',
        'label' => __('Links Color', 'venera' ),
        'name' => 'post_content_links_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e8b30f1cd1f',
        'label' => __('Comment Box', 'venera' ),
        'name' => '',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_51e8b3711cd21',
        'label' => __('Make it Flat', 'venera' ),
        'name' => 'comment_box_make_it_flat',
        'type' => 'true_false',
        'message' => 'Make comment box flat',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_51e8b39a1cd22',
        'label' => __('Background Color', 'venera' ),
        'name' => 'comment_box_background',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51f599236c915',
        'label' => __('Box Border Radius (e.g. 5px)', 'venera' ),
        'name' => 'comment_box_radius',
        'type' => 'text',
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_51e8b3bb1cd23',
        'label' => __('Box Padding (e.g. 10px)', 'venera' ),
        'name' => 'comment_box_padding',
        'type' => 'text',
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_51f59834fe74b',
        'label' => __('Headings Color', 'venera' ),
        'name' => 'comment_box_headings_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51f5984bfe74c',
        'label' => __('Text Color', 'venera' ),
        'name' => 'comment_box_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51f59860fe74d',
        'label' => __('Links Color', 'venera' ),
        'name' => 'comment_box_links_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-blog-posts',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_options-footer-settings',
    'title' => 'Options: Footer Settings',
    'fields' => array (
      array (
        'key' => 'field_51d4c0ce7a547',
        'label' => __('Pre Footer Background Color', 'venera' ),
        'name' => 'pre_footer_background_solid_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51eef4f7af0f4',
        'label' => __('Pre Footer Text Color', 'venera' ),
        'name' => 'pre_footer_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51d4c0f37a548',
        'label' => __('Deep Footer Background Color', 'venera' ),
        'name' => 'deep_footer_background_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51eef4b1af0f3',
        'label' => __('Deep Footer Text Color', 'venera' ),
        'name' => 'deep_footer_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51d4cc8c7a54a',
        'label' => __('Borders Between Footers', 'venera' ),
        'name' => 'borders_between_footers',
        'type' => 'true_false',
        'message' => 'Add border between footers',
        'default_value' => 1,
      ),
      array (
        'key' => 'field_51eef60baf0f5',
        'label' => __('Footer Copyright Text', 'venera' ),
        'name' => 'footer_copyright_text',
        'type' => 'text',
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-footer',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_options-frames',
    'title' => 'Options: Frames',
    'fields' => array (
      array (
        'key' => 'field_51f53ed2ccdf2',
        'label' => __('Browser Frame', 'venera' ),
        'name' => '',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_51f53ee2ccdf3',
        'label' => __('Make it flat', 'venera' ),
        'name' => 'browser_make_it_flat',
        'type' => 'true_false',
        'instructions' => __('If checked - browser frame won\'t have any shadow or gloss', 'venera'),
        'message' => 'Make browser frame flat',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_51f53f2bccdf4',
        'label' => __('Background Color', 'venera' ),
        'name' => 'browser_background_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51f53f5dccdf5',
        'label' => __('Buttons/Icons Color', 'venera' ),
        'name' => 'browser_buttons_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51f53f7cccdf6',
        'label' => __('URL Box Background', 'venera' ),
        'name' => 'browser_url_background',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51f53facccdf7',
        'label' => __('URL Text Color', 'venera' ),
        'name' => 'browser_url_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51f53fc5ccdf8',
        'label' => __('URL Border Radius (e.g. 4px)', 'venera' ),
        'name' => 'browser_url_border_radius',
        'type' => 'text',
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_51f53fd2ccdf9',
        'label' => __('Browser Border Radius (e.g. 4px)', 'venera' ),
        'name' => 'browser_border_radius',
        'type' => 'text',
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-frames',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_options-header-settings',
    'title' => 'Options: Header Settings',
    'fields' => array (
      array (
        'key' => 'field_51d4d461babbd',
        'label' => __('Top Bar Settings', 'venera' ),
        'name' => '',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_51d4d375babbb',
        'label' => __('Background Solid Color', 'venera' ),
        'name' => 'top_bar_background_solid_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51f3f6ea96467',
        'label' => __('Background Image', 'venera' ),
        'name' => 'top_bar_background_image',
        'type' => 'image',
        'save_format' => 'url',
        'preview_size' => 'thumbnail',
        'library' => 'all',
      ),
      array (
        'key' => 'field_51d4e9b1294d2',
        'label' => __('Links and Text Color', 'venera' ),
        'name' => 'top_bar_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51d4ff619474f',
        'label' => __('Top Border Color', 'venera' ),
        'name' => 'top_bar_top_border_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51d4ff3a9474e',
        'label' => __('Bottom Border Color', 'venera' ),
        'name' => 'top_bar_bottom_border_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51d5dd558967e',
        'label' => __('Should top bar stick to the top of the page?', 'venera' ),
        'name' => 'top_bar_fixed_to_top',
        'type' => 'true_false',
        'message' => 'Yes',
        'default_value' => 1,
      ),
      array (
        'key' => 'field_51e0dc14ecbbf',
        'label' => __('Drop Shadow?', 'venera' ),
        'name' => 'top_bar_drop_shadow',
        'type' => 'true_false',
        'message' => 'Top bar should drop shadow',
        'default_value' => 1,
      ),
      array (
        'key' => 'field_520b5edd3b07a',
        'label' => __('Hide Search Box from Top Bar', 'venera' ),
        'name' => 'hide_search_box_from_top_bar',
        'type' => 'true_false',
        'message' => 'Hide search box from top bar',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_52144b7af1e03',
        'label' => __('Top Bar Search Input and Border Color', 'venera' ),
        'name' => 'top_bar_search_input_color',
        'type' => 'color_picker',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_520b5edd3b07a',
              'operator' => '!=',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
      ),
      array (
        'key' => 'field_51d4d427babbc',
        'label' => __('Page Header Settings', 'venera' ),
        'name' => '',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_51d4d4b4babbe',
        'label' => __('Hide page header box by default', 'venera' ),
        'name' => 'default_hide_page_header',
        'type' => 'true_false',
        'message' => 'Yes, hide page header box',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_51e1d0257ccbd',
        'label' => __('Make it flat', 'venera' ),
        'name' => 'default_page_header_make_it_flat',
        'type' => 'true_false',
        'instructions' => __('If checked - all the shadows and gloss will be removed', 'venera'),
        'message' => 'Make page header flat',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_51d4d6d4babc0',
        'label' => __('Background Solid Color', 'venera' ),
        'name' => 'default_page_header_background_solid_color',
        'type' => 'color_picker',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51d4d4b4babbe',
              'operator' => '!=',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
      ),
      array (
        'key' => 'field_51f3f65896466',
        'label' => __('Background Image', 'venera' ),
        'name' => 'default_page_header_background_image',
        'type' => 'image',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51d4d4b4babbe',
              'operator' => '!=',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'save_format' => 'url',
        'preview_size' => 'thumbnail',
        'library' => 'all',
      ),
      array (
        'key' => 'field_51f4242dfee23',
        'label' => __('Title Font Color For Header Box', 'venera' ),
        'name' => 'default_page_header_title_font_color',
        'type' => 'color_picker',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51d4d4b4babbe',
              'operator' => '!=',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
      ),
      array (
        'key' => 'field_51f424b9fee24',
        'label' => __('Sub Title Font Color For Header Box', 'venera' ),
        'name' => 'default_page_header_sub_title_font_color',
        'type' => 'color_picker',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51d4d4b4babbe',
              'operator' => '!=',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-header',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_options-other',
    'title' => 'Options: Other',
    'fields' => array (
      array (
        'key' => 'field_51fa120b76bf0',
        'label' => __('Other Message', 'venera' ),
        'name' => '',
        'type' => 'message',
        'message' => '<h1>Other Settings</h1>
  <p class="howto">These settings are for miscellaneous things used throughout the site.</p>',
      ),
      array (
        'key' => 'field_51fa10dcb3b3e',
        'label' => __('Google Analytics ID', 'venera' ),
        'name' => 'google_analytics_id',
        'type' => 'text',
        'instructions' => __('ID for google analytics code, looks something like: <strong>UA-99999999-1</strong>. Leave blank to not include google analytics code.', 'venera'),
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-other',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_options-ui-elements',
    'title' => 'Options: UI Elements',
    'fields' => array (
      array (
        'key' => 'field_51d4b45006644',
        'label' => __('Items', 'venera' ),
        'name' => '',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_51deeaa02203c',
        'label' => __('Make it flat', 'venera' ),
        'name' => 'item_block_flat',
        'type' => 'true_false',
        'instructions' => __('This will remove gradient from a background and remove a shadow.', 'venera'),
        'message' => 'Make item flat',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_51deea7b2203b',
        'label' => __('Background Color', 'venera' ),
        'name' => 'item_block_background_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51f559a4acb1a',
        'label' => __('Headings Color', 'venera' ),
        'name' => 'item_block_headings_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51deeb5d2203d',
        'label' => __('Text Color', 'venera' ),
        'name' => 'item_block_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51def03a4931c',
        'label' => __('Border Radius (e.g. 4px)', 'venera' ),
        'name' => 'item_block_border_radius',
        'type' => 'text',
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_51def05e4931d',
        'label' => __('Padding ( e.g. 10px)', 'venera' ),
        'name' => 'item_block_padding',
        'type' => 'text',
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_51e0082923b96',
        'label' => __('Text Links Color', 'venera' ),
        'name' => 'item_block_text_links_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e0084723b97',
        'label' => __('Tag Background Color', 'venera' ),
        'name' => 'item_block_tag_background_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e0085b23b98',
        'label' => __('Tag Text Color', 'venera' ),
        'name' => 'item_block_tag_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51d4b48806645',
        'label' => __('Testimonials', 'venera' ),
        'name' => '',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_51e034287d817',
        'label' => __('Make it flat', 'venera' ),
        'name' => 'testimonial_make_it_flat',
        'type' => 'true_false',
        'instructions' => __('this will remove shadows from testimonial box and author photo', 'venera'),
        'message' => 'Make testimonial flat',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_51e02f497d813',
        'label' => __('Background Color', 'venera' ),
        'name' => 'testimonial_background_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e04f93bbb52',
        'label' => __('Heading Color', 'venera' ),
        'name' => 'testimonial_heading_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e02f717d814',
        'label' => __('Text Color', 'venera' ),
        'name' => 'testimonial_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e034a9dee1c',
        'label' => __('Border Radius (e.g. 5px)', 'venera' ),
        'name' => 'testimonial_border_radius',
        'type' => 'text',
        'default_value' => '',
        'formatting' => 'none',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_51e034dddee1d',
        'label' => __('Box Padding (e.g. 10px)', 'venera' ),
        'name' => 'testimonial_box_padding',
        'type' => 'text',
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_51e02f877d815',
        'label' => __('Highlight Color', 'venera' ),
        'name' => 'testimonial_highlight_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e033977d816',
        'label' => __('Author Text Color', 'venera' ),
        'name' => 'testimonial_author_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e04e53f1d86',
        'label' => __('Author Border Color', 'venera' ),
        'name' => 'testimonial_border_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51d4b8ea06646',
        'label' => __('Accordion', 'venera' ),
        'name' => '',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_51e052a5d2bcc',
        'label' => __('Make it flat', 'venera' ),
        'name' => 'accordion_make_it_flat',
        'type' => 'true_false',
        'instructions' => __('This will make accordion flat and will remove all shadows', 'venera'),
        'message' => 'Make accordion flat',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_51e05039d2bc6',
        'label' => __('Tab Header Background Color', 'venera' ),
        'name' => 'accordion_tab_header_bg',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e05062d2bc7',
        'label' => __('Tab Header Text Color', 'venera' ),
        'name' => 'accordion_tab_header_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e086261a78d',
        'label' => __('Tab Header Active Background', 'venera' ),
        'name' => 'accordion_tab_header_active_bg',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e086501a78e',
        'label' => __('Tab Header Active Text Color', 'venera' ),
        'name' => 'accordion_tab_header_active_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e06377dabc8',
        'label' => __('Icon Color', 'venera' ),
        'name' => 'accordion_icon_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e088084a710',
        'label' => __('Icon Active Color', 'venera' ),
        'name' => 'accordion_icon_active_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e050b3d2bc9',
        'label' => __('Tab Content Background Color', 'venera' ),
        'name' => 'accordion_tab_content_bg',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e05233d2bca',
        'label' => __('Tab Content Text Color', 'venera' ),
        'name' => 'accordion_tab_content_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e0508ad2bc8',
        'label' => __('Border Radius (e.g. 5px)', 'venera' ),
        'name' => 'accordion_border_radius',
        'type' => 'text',
        'default_value' => '',
        'formatting' => 'none',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_51e083b91a784',
        'label' => __('Tabs', 'venera' ),
        'name' => '',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_51e085771a78c',
        'label' => __('Make it flat', 'venera' ),
        'name' => 'tabs_make_it_flat',
        'type' => 'true_false',
        'instructions' => __('This will remove all shadows from tabs', 'venera'),
        'message' => 'Make tabs flat',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_51e083d01a785',
        'label' => __('Tab Header Text Color', 'venera' ),
        'name' => 'tabs_tab_header_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e084281a786',
        'label' => __('Tab Header Background', 'venera' ),
        'name' => 'tabs_tab_header_bg',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e084bc1a788',
        'label' => __('Tab Header Active Text Color', 'venera' ),
        'name' => 'tabs_tab_header_active_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e0845b1a787',
        'label' => __('Tab Header Active Background', 'venera' ),
        'name' => 'tabs_tab_header_active_bg',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e085021a789',
        'label' => __('Tab Content Background', 'venera' ),
        'name' => 'tabs_tab_content_bg',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e0854b1a78a',
        'label' => __('Tab Content Text Color', 'venera' ),
        'name' => 'tabs_tab_content_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e0855f1a78b',
        'label' => __('Tabs Border Radius (e.g. 10px)', 'venera' ),
        'name' => 'tabs_border_radius',
        'type' => 'text',
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_51e0ba05f8d00',
        'label' => __('Pricing Table', 'venera' ),
        'name' => '',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_51e0ba35f8d03',
        'label' => __('Make it flat', 'venera' ),
        'name' => 'pricing_make_it_flat',
        'type' => 'true_false',
        'instructions' => __('That will remove any shadows from pricing table box', 'venera'),
        'message' => 'Make pricing table flat',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_51e0ba11f8d01',
        'label' => __('Background Color', 'venera' ),
        'name' => 'pricing_background_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e0c05534209',
        'label' => __('Heading Color', 'venera' ),
        'name' => 'pricing_heading_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e0ba22f8d02',
        'label' => __('Text Color', 'venera' ),
        'name' => 'pricing_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e0bedb774e1',
        'label' => __('Price Period Color', 'venera' ),
        'name' => 'pricing_period_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e0bbb7f8d08',
        'label' => __('Feature Highlight Color', 'venera' ),
        'name' => 'pricing_highlight_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e0bfa35461a',
        'label' => __('Border Radius (e.g. 8px)', 'venera' ),
        'name' => 'pricing_border_radius',
        'type' => 'text',
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_51e1887aef0a3',
        'label' => __('Buttons', 'venera' ),
        'name' => '',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_51e18887ef0a4',
        'label' => __('Style', 'venera' ),
        'name' => 'button_style',
        'type' => 'select',
        'choices' => array (
          'default' => __('Default', 'venera'),
          'flat' => __('Flat', 'venera'),
          'abs_flat' => __('Absolutely Flat', 'venera'),
        ),
        'default_value' => 'default',
        'allow_null' => 0,
        'multiple' => 0,
      ),
      array (
        'key' => 'field_51e18b1cef0a7',
        'label' => __('Border Radius (e.g. 4px)', 'venera' ),
        'name' => 'button_border_radius',
        'type' => 'text',
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_51e18a0fef0a5',
        'label' => __('Default Button Background Color', 'venera' ),
        'name' => 'button_default_background_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e18ae6ef0a6',
        'label' => __('Default Button Text Color', 'venera' ),
        'name' => 'button_default_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e1ac9112830',
        'label' => __('Primary Button Background Color', 'venera' ),
        'name' => 'button_primary_background_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e1acbd12831',
        'label' => __('Primary Button Text Color', 'venera' ),
        'name' => 'button_primary_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e1ba2a12833',
        'label' => __('Info Button Background Color', 'venera' ),
        'name' => 'button_info_background_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e1ba4e12834',
        'label' => __('Info Button Text Color', 'venera' ),
        'name' => 'button_info_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e1ba6412835',
        'label' => __('Success Button Background Color', 'venera' ),
        'name' => 'button_success_background_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e1bae51283a',
        'label' => __('Success Button Text Color', 'venera' ),
        'name' => 'button_success_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e1ba7b12836',
        'label' => __('Warning Button Background Color', 'venera' ),
        'name' => 'button_warning_background_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e1bad112839',
        'label' => __('Warning Button Text Color', 'venera' ),
        'name' => 'button_warning_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e1baa212837',
        'label' => __('Danger Button Background Color', 'venera' ),
        'name' => 'button_danger_background_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
      array (
        'key' => 'field_51e1baba12838',
        'label' => __('Danger Button Text Color', 'venera' ),
        'name' => 'button_danger_text_color',
        'type' => 'color_picker',
        'default_value' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-ui-elements',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_package-information',
    'title' => 'Package Information',
    'fields' => array (
      array (
        'key' => 'field_5158b50a23716',
        'label' => __('Package Price', 'venera' ),
        'name' => 'package_price',
        'type' => 'number',
        'required' => 1,
        'default_value' => '',
        'min' => '',
        'max' => '',
        'step' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_5158f0006039e',
        'label' => __('Price Currency', 'venera' ),
        'name' => 'price_currency',
        'type' => 'text',
        'instructions' => __('Currency value to show next to the price (e.g. $)', 'venera'),
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_5158f0376039f',
              'operator' => '!=',
              'value' => 'none',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_5158b55323717',
        'label' => __('Price Period', 'venera' ),
        'name' => 'price_period',
        'type' => 'text',
        'instructions' => __('A time period which is covered by package price', 'venera'),
        'default_value' => 'mo',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_5158b7bd23718',
        'label' => __('Package Description', 'venera' ),
        'name' => 'package_description',
        'type' => 'textarea',
        'instructions' => __('Text for a highlighted box', 'venera'),
        'default_value' => '',
        'formatting' => 'br',
        'maxlength' => '',
        'placeholder' => '',
      ),
      array (
        'key' => 'field_5158ba7c4f74f',
        'label' => __('Button Label', 'venera' ),
        'name' => 'button_label',
        'type' => 'text',
        'required' => 1,
        'default_value' => 'Select This Plan',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_5158bb634f750',
        'label' => __('Package Link', 'venera' ),
        'name' => 'package_link',
        'type' => 'text',
        'instructions' => __('Link to the registration page of the selected package', 'venera'),
        'required' => 1,
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_5158daed08bd1',
        'label' => __('Table Position', 'venera' ),
        'name' => 'position',
        'type' => 'number',
        'instructions' => __('Position from left in the pricing table', 'venera'),
        'default_value' => 1,
        'min' => '',
        'max' => '',
        'step' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'venera_pricing',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_page-custom-fields',
    'title' => 'Page Custom Fields',
    'fields' => array (
      array (
        'key' => 'field_51b549d86a462',
        'label' => __('Page Settings', 'venera' ),
        'name' => 'Header_Settings',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_51b53bdff58b9',
        'label' => __('Use Title as a Header', 'venera' ),
        'name' => 'use_title_as_a_header',
        'type' => 'true_false',
        'instructions' => __('Uncheck if you don\'t want a page title to appear as a header', 'venera'),
        'message' => 'Use title as a page header',
        'default_value' => 1,
      ),
      array (
        'key' => 'field_51dacb673700e',
        'label' => __('Make top bar transparent', 'venera' ),
        'name' => 'inversed_top_bar',
        'type' => 'true_false',
        'message' => 'Make top bar the same color as background',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_520b6c4efc8a2',
        'label' => __('Extra padding on top', 'venera' ),
        'name' => 'extra_padding_on_top',
        'type' => 'true_false',
        'instructions' => __('Check this if you want to add extra padding on top of the page', 'venera'),
        'message' => 'Add extra padding',
        'default_value' => 0,
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'page',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_portfolio-item',
    'title' => 'Portfolio Item',
    'fields' => array (
      array (
        'key' => 'field_51c01243bdbfa',
        'label' => __('Portfolio Settings', 'venera' ),
        'name' => '',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_51eca002fb5a5',
        'label' => __('Content Type', 'venera' ),
        'name' => 'content_type',
        'type' => 'select',
        'choices' => array (
          'image' => __('Image(s)', 'venera'),
          'video' => __('Video', 'venera'),
        ),
        'default_value' => 'image',
        'allow_null' => 0,
        'multiple' => 0,
      ),
      array (
        'key' => 'field_51bee639bf231',
        'label' => __('Images', 'venera' ),
        'name' => 'images',
        'type' => 'gallery',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51eca002fb5a5',
              'operator' => '==',
              'value' => 'image',
            ),
          ),
          'allorany' => 'all',
        ),
        'preview_size' => 'thumbnail',
      ),
      array (
        'key' => 'field_51eca164156d9',
        'label' => __('Image size', 'venera' ),
        'name' => 'image_size',
        'type' => 'text',
        'instructions' => __('Enter image size. Example: thumbnail, medium, large, full or other sizes defined by current theme. Alternatively enter image size in pixels: 200x100 (Width x Height). Leave empty to use \'thumbnail\' size.', 'venera'),
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51eca002fb5a5',
              'operator' => '==',
              'value' => 'image',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_51faba38a697d',
        'label' => __('Show Image Lightbox on Click', 'venera' ),
        'name' => 'portfolio_show_image_lightbox',
        'type' => 'true_false',
        'instructions' => __('Check this if you want a lightbox to appera when you click on the image of portfoio item', 'venera'),
        'message' => 'Show image lightbox on click',
        'default_value' => 1,
      ),
      array (
        'key' => 'field_51fabc2ad81c7',
        'label' => __('Custom image for lightbox', 'venera' ),
        'name' => 'custom_image_for_lightbox',
        'type' => 'image',
        'instructions' => __('You can set a set of custom image to be shown when you activate a lightbox, if you don\'t select anything it will show images that you selected before in field called "Images".', 'venera'),
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51faba38a697d',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'save_format' => 'id',
        'preview_size' => 'thumbnail',
        'library' => 'all',
      ),
      array (
        'key' => 'field_51eca0e0fb5a6',
        'label' => __('Video Link', 'venera' ),
        'name' => 'video_link',
        'type' => 'text',
        'instructions' => __('Link to the video. More about supported formats at <a href="http://codex.wordpress.org/Embeds#Okay.2C_So_What_Sites_Can_I_Embed_From.3F" target="_blank">WordPress codex page</a>', 'venera'),
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51eca002fb5a5',
              'operator' => '==',
              'value' => 'video',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_5161cb9b06dcf',
        'label' => __('Featured', 'venera' ),
        'name' => 'featured',
        'type' => 'true_false',
        'message' => 'Featured portfolio item',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_5178b9bc006ee',
        'label' => __('Frame Type', 'venera' ),
        'name' => 'frame_type',
        'type' => 'select',
        'choices' => array (
          'browser' => __('Browser', 'venera'),
          'phone' => __('Phone', 'venera'),
          'picture' => __('Picture', 'venera'),
          'plain' => __('Plain', 'venera'),
          'none' => __('No Frame', 'venera'),
        ),
        'default_value' => 'browser',
        'allow_null' => 0,
        'multiple' => 0,
      ),
      array (
        'key' => 'field_51ec83b9f61f5',
        'label' => __('Browser URL text', 'venera' ),
        'name' => 'browser_url_text',
        'type' => 'text',
        'instructions' => __('Text that appears in the browser url bar', 'venera'),
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_5178b9bc006ee',
              'operator' => '==',
              'value' => 'browser',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_51e63b0f44df1',
        'label' => __('Description Column Position', 'venera' ),
        'name' => 'portfolio_description_column_position',
        'type' => 'radio',
        'instructions' => __('Where do you want the description to be related to the image.', 'venera'),
        'choices' => array (
          'left' => __('Left', 'venera'),
          'right' => __('Right', 'venera'),
          'bottom' => __('Bottom', 'venera'),
        ),
        'other_choice' => 0,
        'save_other_choice' => 0,
        'default_value' => 'right',
        'layout' => 'horizontal',
      ),
      array (
        'key' => 'field_51e63a1544df0',
        'label' => __('Description Column Width', 'venera' ),
        'name' => 'portfolio_description_column_width',
        'type' => 'select',
        'instructions' => __('Select a width of the description block for the portfolio item. Note: For the mobile portfolio item type recommended width is 65%.', 'venera'),
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51e63b0f44df1',
              'operator' => '!=',
              'value' => 'bottom',
            ),
          ),
          'allorany' => 'all',
        ),
        'choices' => array (
          3 => '25%',
          4 => '35%',
          6 => '50%',
          8 => '65%',
          9 => '75%',
        ),
        'default_value' => 6,
        'allow_null' => 0,
        'multiple' => 0,
      ),
      array (
        'key' => 'field_51f6e0a4a0dac',
        'label' => __('Wrap description in a box', 'venera' ),
        'name' => 'portfolio_wrap_description',
        'type' => 'true_false',
        'instructions' => __('Wrap the description content into the box - great for dark backgrounds, this will allow text to pop.', 'venera'),
        'message' => 'Yes, wrap description in a box',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_51ec8ae767422',
        'label' => __('Link to external website', 'venera' ),
        'name' => 'link_to_external_website',
        'type' => 'text',
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'venera_portfolio',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_slide-settings',
    'title' => 'Slide Settings',
    'fields' => array (
      array (
        'key' => 'field_51c89223be596',
        'label' => __('Layout type', 'venera' ),
        'name' => 'layout_type',
        'type' => 'select',
        'choices' => array (
          'web_app_single' => __('Web application - single shot centered', 'venera' ),
          'web_app_aside' => __('Web application - single shot aside', 'venera' ),
          'web_app_three' => __('Web application - three shots lined up', 'venera' ),
          'web_app_three_behind' => __('Web application - three shots behind each other', 'venera' ),
          'mobile_app' => __('Mobile Application', 'venera' ),
        ),
        'default_value' => 'web_app_single',
        'allow_null' => 0,
        'multiple' => 0,
      ),
      array (
        'key' => 'field_51c170cad6916',
        'label' => __('Slide Position', 'venera' ),
        'name' => 'slide_position',
        'type' => 'number',
        'instructions' => __('Set the position in which slider will appear.', 'venera'),
        'default_value' => '',
        'min' => '',
        'max' => '',
        'step' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'venera_slide',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_team-members',
    'title' => 'Team Members',
    'fields' => array (
      array (
        'key' => 'field_5167799b9b44c',
        'label' => __('Sub Title', 'venera' ),
        'name' => 'sub_title',
        'type' => 'text',
        'instructions' => __('Text that goes under member\'s name.', 'venera'),
        'default_value' => '',
        'formatting' => 'none',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_51677ee0b632d',
        'label' => __('Has Contact Information', 'venera' ),
        'name' => 'has_contact_information',
        'type' => 'true_false',
        'instructions' => __('Do you want to show contact information for team members.', 'venera'),
        'message' => 'Show contact information',
        'default_value' => 1,
      ),
      array (
        'key' => 'field_516710c2ee912',
        'label' => __('Twitter URL', 'venera' ),
        'name' => 'twitter_url',
        'type' => 'text',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51677ee0b632d',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
        'formatting' => 'none',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_5167110eee913',
        'label' => __('Facebook URL', 'venera' ),
        'name' => 'facebook_url',
        'type' => 'text',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51677ee0b632d',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
        'formatting' => 'none',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_5167111cee914',
        'label' => __('LinkedIn URL', 'venera' ),
        'name' => 'linkedin_url',
        'type' => 'text',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51677ee0b632d',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
        'formatting' => 'none',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_5167964148493',
        'label' => __('Pinterest URL', 'venera' ),
        'name' => 'pinterest_url',
        'type' => 'text',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51677ee0b632d',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
        'formatting' => 'none',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_5167114aee916',
        'label' => __('Email', 'venera' ),
        'name' => 'email',
        'type' => 'text',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51677ee0b632d',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
        'formatting' => 'none',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_5167115dee917',
        'label' => __('Phone Number', 'venera' ),
        'name' => 'phone_number',
        'type' => 'text',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_51677ee0b632d',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
        'formatting' => 'none',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'venera_team_member',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_testimonials',
    'title' => 'Testimonials',
    'fields' => array (
      array (
        'key' => 'field_51b2cc43be631',
        'label' => __('Person Name', 'venera' ),
        'name' => 'person_name',
        'type' => 'text',
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_51b2cd09be632',
        'label' => __('Company Name', 'venera' ),
        'name' => 'company_name',
        'type' => 'text',
        'default_value' => '',
        'formatting' => 'html',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'venera_testimonial',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
}
?>